import crypto from "crypto";
import type { ComicChapter, ComicDetails, ComicSummary } from "@/lib/comic/types";

const APP_SECRET = "18comicAPPContent";
const DATA_SECRET = "185Hcomic3PAPP7R";
const DOMAIN_LIST_URL = "https://rup4a04-c02.tos-cn-hongkong.bytepluses.com/newsvr-2025.txt";
const DOMAIN_LIST_SECRET = "diosfjckwpqpdfjkvnqQjsik";
const JM_VERSION = "2.0.16";
const UA = "Mozilla/5.0 (Linux; Android 10; K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.0.0 Mobile Safari/537.36";
export const JM_IMAGE_HOST = "https://cdn-msp.jmapinodeudzn.net";
const FALLBACK_DOMAINS = ["www.cdnhjk.net", "www.cdngwc.cc", "www.cdngwc.net", "www.cdngwc.club", "www.cdnutc.me", "www.cdntwice.org", "www.cdnntr.cc"];
function md5Hex(input: string | Buffer): string { return crypto.createHash("md5").update(input as any).digest("hex"); }
function apiHeaders(time: number): Record<string, string> { return { Accept: "*/*", "Accept-Language": "zh-CN,zh;q=0.9", Authorization: "Bearer", token: md5Hex(Buffer.from(`${time}${APP_SECRET}`, "utf8")), tokenparam: `${time},${JM_VERSION}`, "User-Agent": UA, "X-Requested-With": "com.example.app" }; }
function extractJson(text: string): string { let start = 0; while (start < text.length && text[start] !== "{" && text[start] !== "[") start++; let end = text.length - 1; while (end > start && text[end] !== "}" && text[end] !== "]") end--; return text.substring(start, end + 1); }
function aesEcbDecrypt(secret: string, b64: string): string { const key = Buffer.from(md5Hex(Buffer.from(secret, "utf8")), "utf8"); const d = crypto.createDecipheriv("aes-256-ecb", key, null); d.setAutoPadding(true); return Buffer.concat([d.update(Buffer.from(b64, "base64")), d.final()]).toString("utf8"); }
let cachedDomains: string[] | null = null; let cachedAt = 0;
async function getDomains(): Promise<string[]> { const now = Date.now(); if (cachedDomains && now - cachedAt < 30 * 60 * 1000) return cachedDomains; try { const res = await fetch(DOMAIN_LIST_URL, { headers: { "User-Agent": UA }, cache: "no-store" }); if (res.ok) { const raw = (await res.text()).replace(/^\uFEFF/, "").trim(); const json = JSON.parse(extractJson(aesEcbDecrypt(DOMAIN_LIST_SECRET, raw))); const servers: string[] = Array.isArray(json.Server) ? json.Server : []; if (servers.length) { cachedDomains = servers; cachedAt = now; return servers; } } } catch {} cachedDomains = FALLBACK_DOMAINS; cachedAt = now; return FALLBACK_DOMAINS; }
async function jmGet(path: string): Promise<any> { const domains = await getDomains(); let lastError = "禁漫天堂暂时无法连接"; for (const host of domains) { try { const time = Math.floor(Date.now() / 1000); const res = await fetch(`https://${host}${path}`, { headers: apiHeaders(time), cache: "no-store" }); if (!res.ok) { lastError = `${host} 返回 HTTP ${res.status}`; continue; } const json = await res.json(); if (typeof json.data !== "string") { lastError = `${host} 数据异常`; continue; } return JSON.parse(extractJson(aesEcbDecrypt(`${time}${DATA_SECRET}`, json.data))); } catch (e) { lastError = e instanceof Error ? e.message : String(e); } } throw new Error(lastError); }
function parseSummary(item: any): ComicSummary { const id = String(item.id); const tags: string[] = []; if (item?.category?.title) tags.push(item.category.title); if (item?.category_sub?.title) tags.push(item.category_sub.title); return { id, title: item.name ?? "", author: item.author ?? undefined, cover: `${JM_IMAGE_HOST}/media/albums/${id}_3x4.jpg`, tags }; }
export type JmPage = { comics: ComicSummary[]; total: number; page: number };
export async function getCategoryComics(theme: string, ordering: string, page: number): Promise<JmPage> { const o = ordering || "mr"; if (!theme) { const json = await jmGet(`/latest?page=${page}`); const list: any[] = Array.isArray(json.list) ? json.list : Array.isArray(json) ? json : []; return { comics: list.filter(Boolean).map(parseSummary), total: 0, page }; } const json = await jmGet(`/categories/filter?o=${o}&c=${encodeURIComponent(theme)}&page=${page}`); const list: any[] = Array.isArray(json.content) ? json.content : []; return { comics: list.filter(Boolean).map(parseSummary), total: Number(json.total) || 0, page }; }
export async function search(keyword: string, ordering: string, page: number): Promise<JmPage> { const kw = encodeURIComponent(keyword.trim()).replace(/%20/g, "+"); let path = `/search?search_query=${kw}&o=${ordering || "mr"}`; if (page > 1) path += `&page=${page}`; const json = await jmGet(path); const list: any[] = Array.isArray(json.content) ? json.content : []; return { comics: list.filter(Boolean).map(parseSummary), total: Number(json.total) || 0, page }; }
export async function getComicInfo(id: string): Promise<ComicDetails> { const albumId = id.startsWith("jm") ? id.substring(2) : id; const data = (await jmGet(`/album?id=${albumId}`)) || {}; const chapters: ComicChapter[] = []; const series: any[] = Array.isArray(data.series) ? data.series.filter((e: any) => e && e.id != null).sort((a: any, b: any) => Number(a.sort) - Number(b.sort)) : []; if (!series.length) chapters.push({ id: albumId, title: "第1話", comicId: albumId, section: "章节", slot: "0" }); else for (const e of series) chapters.push({ id: String(e.id), title: (e && e.name ? String(e.name) : "").trim() || `第${e.sort}話`, comicId: albumId, section: "章节", slot: String(chapters.length) }); let updateTime = ""; if (data.addtime) { const dt = new Date(Number(data.addtime) * 1000); updateTime = `${dt.getFullYear()}-${dt.getMonth() + 1}-${dt.getDate()}`; } const authorArr = Array.isArray(data.author) ? data.author.filter(Boolean) : []; const author = authorArr.length ? authorArr.join(", ") : typeof data.author === "string" ? data.author : undefined; return { id: albumId, title: data.name ?? "", author, cover: `${JM_IMAGE_HOST}/media/albums/${albumId}_3x4.jpg`, tags: Array.isArray(data.tags) ? data.tags.filter(Boolean) : [], description: data.description ?? "", updateTime, chapters }; }
function scrambleNum(epId: number, pictureName: string): number { if (epId < 220980) return 0; if (epId < 268850) return 10; const hash = md5Hex(Buffer.from(`${epId}${pictureName}`, "utf8")); return (hash.charCodeAt(hash.length - 1) % (epId > 421926 ? 8 : 10)) * 2 + 2; }
export type JmChapterImage = { url: string; num: number };
export async function getChapterImages(epId: string): Promise<JmChapterImage[]> { const data = await jmGet(`/chapter?id=${epId}`); return (Array.isArray(data.images) ? data.images : []).filter((n: any) => typeof n === "string").map((name: string) => { const dot = name.lastIndexOf("."); const base = dot >= 0 ? name.substring(0, dot) : name; return { url: `${JM_IMAGE_HOST}/media/photos/${epId}/${name}`, num: name.toLowerCase().endsWith(".gif") ? 0 : scrambleNum(Number(epId), base) }; }); }
export async function getHomeIndex(): Promise<Record<string, ComicSummary[]>> { const json = await jmGet("/latest?page=1"); const list: any[] = Array.isArray(json.list) ? json.list : Array.isArray(json) ? json : []; return { 最新: list.map(parseSummary) }; }
